import 'package:flutter/material.dart';
import 'package:foodfiesta/models/meal_model.dart';
import 'package:foodfiesta/models/home_category_model.dart';

const HomeCategoryDataModel = const [
  HomeCategoryModel(
      id: 'c1', title: 'Italian', color: Color.fromARGB(255, 255, 157, 0)),
  HomeCategoryModel(
      id: 'c2', title: 'Arabic', color: Color.fromARGB(255, 255, 2, 2)),
  HomeCategoryModel(
      id: 'c3', title: 'Pakistani', color: Color.fromARGB(255, 255, 226, 122)),
  HomeCategoryModel(
      id: 'c4', title: 'Afghani', color: Color.fromARGB(255, 168, 171, 150)),
  HomeCategoryModel(
      id: 'c5', title: 'SeaFood', color: Color.fromARGB(255, 75, 255, 9)),
  HomeCategoryModel(
      id: 'c6', title: 'Turkish', color: Color.fromARGB(255, 9, 255, 226)),
  HomeCategoryModel(
      id: 'c7', title: 'Indian', color: Color.fromARGB(255, 0, 94, 255)),
  HomeCategoryModel(
      id: 'c8', title: 'Balochi', color: Color.fromARGB(255, 186, 95, 255)),
  HomeCategoryModel(
      id: 'c9', title: 'Chines', color: Color.fromARGB(255, 255, 79, 199)),
  HomeCategoryModel(
      id: 'c10', title: 'FastFood', color: Color.fromARGB(255, 225, 172, 0)),
];

const EachMixModeldata = const [
  EachMixModel(
      id: 'm1',
      categoriesid: ['c3', 'c7'],
      title: 'Chapli Kabab',
      imageurl:
          'https://res.cloudinary.com/www-travelpakistani-com/image/upload/v1661615915/Chapli_Kebab_travelpakistani.png',
      ingredients: [
        'cooking spray',
        '1 large egg, lightly beaten',
        '1 pound ground beef',
        '1 red onion, finely chopped',
        '1 red onion, finely chopped',
        '¼ cup finely chopped cilantro',
        '¼ cup finely chopped mint',
        '2 teaspoons ginger-garlic paste',
        '2 teaspoons coriander seeds, crushed',
        '1 teaspoon salt',
        '¾ teaspoon ground cumin',
        '¾ teaspoon ground cayenne pepper',
        '2 tomato, sliced into rounds',
        '¼ cup vegetable oil for frying, or more as needed'
      ],
      steps: [
        'Coat a small skillet with cooking spray and place over medium-high heat. Cook and stir beaten egg in the hot skillet until scrambled and set, 3 to 5 minutes.',
        'Combine scrambled egg, beef, onion, chopped tomato, cilantro, mint, ginger-garlic paste, coriander seeds, salt, cumin, and cayenne pepper in a large bowl; mix by hand until well combined. Shape mixture into patties. Press a tomato slice into the center of each patty.',
        'Heat oil in a deep skillet to 375 degrees F (190 degrees C). Cook patties in hot oil in batches until charred, 4 to 6 minutes per side.'
      ],
      isoilfree: false,
      issaltfree: true,
      isvegetarian: false,
      duration: 45,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm2',
      categoriesid: ['c3', 'c7'],
      title: 'Palak Paneer',
      imageurl:
          'https://img.freepik.com/free-photo/high-angle-pakistani-food-bowl_23-2148825107.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: false,
      isvegetarian: true,
      duration: 60,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm3',
      categoriesid: ['c3', 'c7'],
      title: 'Seekh Kabab',
      imageurl:
          'https://media.istockphoto.com/id/501266025/photo/seekh-kabab-5.jpg?s=612x612&w=0&k=20&c=D6JXEtB4OLF9A91nAfDYLlh507LlbmP_M9PZBoJqD9Q=',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: false,
      issaltfree: true,
      isvegetarian: false,
      duration: 30,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm4',
      categoriesid: ['c3', 'c7'],
      title: 'Mutton Korma',
      imageurl:
          'https://thumbs.dreamstime.com/b/indian-pakistani-food-cooked-meal-chicken-masala-kaleji-gravy-chapati-salad-delicious-meat-male-174029398.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: false,
      duration: 120,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm5',
      categoriesid: ['c1'],
      title: 'Spaghetti',
      imageurl:
          'https://t3.ftcdn.net/jpg/01/09/75/90/360_F_109759077_SVp62TBuHkSn3UsGW4dBOm9R0ALVetYw.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 20,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm6',
      categoriesid: ['c1'],
      title: 'Fiorentina Steak',
      imageurl:
          'https://www.billyparisi.com/wp-content/uploads/2018/12/bistecca-12.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 150,
      complaxity: Complaxity.Hard,
      affordability: Affordability.Luxurious),
  EachMixModel(
      id: 'm7',
      categoriesid: ['c1'],
      title: 'Truffles',
      imageurl:
          'https://i0.wp.com/www.pardonyourfrench.com/wp-content/uploads/2024/01/French-chocolate-truffles-13.jpg?fit=1200%2C1798&ssl=1',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 40,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm8',
      categoriesid: ['c1'],
      title: 'Napoletana Pizza',
      imageurl:
          'https://fornopiombo.com/cdn/shop/articles/How-to-Make-Neapolitan-Pizza-At-Home.jpg?v=1654552141',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 35,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm9',
      categoriesid: ['c1'],
      title: 'Lasagne',
      imageurl:
          'https://keepingitsimpleitalian.com/wp-content/uploads/2022/11/lasagna-bolognese-slice.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 42,
      complaxity: Complaxity.Hard,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm10',
      categoriesid: ['c2'],
      title: 'Dolma',
      imageurl:
          'https://www.unicornsinthekitchen.com/wp-content/uploads/2019/08/Dolma-feature-image.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 70,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm11',
      categoriesid: ['c2'],
      title: 'Falafel',
      imageurl:
          'https://static01.nyt.com/images/2024/01/10/multimedia/10Felafel-wqbp/10Felafel-wqbp-superJumbo.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 38,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm12',
      categoriesid: ['c2'],
      title: 'Fesikh',
      imageurl:
          'https://img.freepik.com/premium-photo/cuisine-from-europe-fish-stew-is-known-as-fesikh-feseekh-egypt-salted-fish-is-consumed-durin_410516-112994.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 48,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm13',
      categoriesid: ['c2'],
      title: 'Kabsa',
      imageurl:
          'https://onestophalal.com/cdn/shop/articles/lamb_kabsa-1699770613303_1200x.jpg?v=1699770657',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 150,
      complaxity: Complaxity.Hard,
      affordability: Affordability.Luxurious),
  EachMixModel(
      id: 'm14',
      categoriesid: ['c4'],
      title: 'Kabuli Pulao',
      imageurl:
          'https://www.masala.tv/wp-content/uploads/2021/09/Kabuli-Pulao-web.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 120,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm15',
      categoriesid: ['c4'],
      title: 'Afghan Kabab',
      imageurl:
          'https://lh3.googleusercontent.com/proxy/Y7XiZD2HpQbwLSCwUWYiqthAzERFdNKsCGvgzqpoI7Ffyne2lxmq0dFYOCyNtn_rGKFY-Tr30gH2ff-6Vd93-azwDp5V9ceFMejtxANdMP8rxBnL8Bz20Tdb-pt_JpWhSYkJLg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 40,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm16',
      categoriesid: ['c4'],
      title: 'Qormah',
      imageurl:
          'https://afghancooks.com/wp-content/uploads/2022/09/IMG-1912-jpg-scaled.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 49,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm17',
      categoriesid: ['c4'],
      title: 'Afghan Karahi',
      imageurl: 'https://i.ytimg.com/vi/dD15SbuPgSg/maxresdefault.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 60,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm18',
      categoriesid: ['c4'],
      title: 'Bolani',
      imageurl:
          'https://images.getrecipekit.com/20240409133114-bolani1.jpg?aspect_ratio=16:9&quality=90&',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 30,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm19',
      categoriesid: ['c5'],
      title: 'Shrimp',
      imageurl:
          'https://www.onceuponachef.com/images/2024/04/garlic-butter-shrimp03794-2.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 45,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Luxurious),
  EachMixModel(
      id: 'm20',
      categoriesid: ['c5'],
      title: 'Salmon',
      imageurl:
          'https://www.vitalchoice.com/blog/wp-content/uploads/2023/05/copper-river-king-salmon-recipe-hero.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 15,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm21',
      categoriesid: ['c5'],
      title: 'Tilapia',
      imageurl:
          'https://www.allrecipes.com/thmb/qlDqag6_s0LErI2ltLOwnIKNBJ4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/201934-PanSearedTilapiaRecipe-mfs-1X2-13feffbafb2c49d9a45cee4c118770bc.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 45,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm22',
      categoriesid: ['c5'],
      title: 'mollusks dish',
      imageurl:
          'https://cdn.tasteatlas.com//images/dishes/4ec94f7c69c94587a34cf865a90385c8.jpg?w=375&h=280',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 15,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm23',
      categoriesid: ['c6'],
      title: 'Baklava',
      imageurl:
          'https://cleobuttera.com/wp-content/uploads/2018/03/lifted-baklava-720x540.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 35,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm24',
      categoriesid: ['c6'],
      title: 'Manti',
      imageurl:
          'https://flavortheglobe.com/wp-content/uploads/2023/05/Turkish-Ravioli-Recipe-Twitter-480x360.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 45,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm25',
      categoriesid: ['c6'],
      title: 'Kofta',
      imageurl:
          'https://www.recipetineats.com/tachyon/2014/11/Lamb-Koftas_7.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 40,
      complaxity: Complaxity.Hard,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm26',
      categoriesid: ['c6'],
      title: 'Pide',
      imageurl:
          'https://www.giverecipe.com/wp-content/uploads/2020/08/How-to-make-Turkish-pide.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 15,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm27',
      categoriesid: ['c8'],
      title: 'Khadi Kabab',
      imageurl:
          'https://static.tossdown.com/images/8639e3c2-5c50-4486-b5d8-341565f8adbe.webp',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 150,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Luxurious),
  EachMixModel(
      id: 'm28',
      categoriesid: ['c8'],
      title: 'Sajji',
      imageurl:
          'https://openmenupk.s3.ap-south-1.amazonaws.com/wp-content/uploads/2022/11/29102510/sajji-cover.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 55,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm29',
      categoriesid: ['c8'],
      title: 'Dumpukht',
      imageurl: 'https://i.ytimg.com/vi/Wp5yDBBpXiA/maxresdefault.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 160,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Luxurious),
  EachMixModel(
      id: 'm30',
      categoriesid: ['c8'],
      title: 'Bagoosht',
      imageurl:
          'https://i0.wp.com/thecaspianchef.com/wp-content/uploads/2020/04/Abgoosht2.jpeg?fit=3072%2C1728&ssl=1',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 90,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm31',
      categoriesid: ['c9'],
      title: 'Lamian',
      imageurl:
          'https://upload.wikimedia.org/wikipedia/commons/0/0c/%E5%85%B0%E5%B7%9E%E7%89%9B%E8%82%89%E9%9D%A2.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 20,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm32',
      categoriesid: ['c9'],
      title: 'Beef noodle soup',
      imageurl:
          'https://www.thespruceeats.com/thmb/ABkIbUeYTsxUQZYiFdJTzIK_r9s=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/taiwanese-beef-noodle-soup-4777014-hero-01-e06a464badec476684e513cad44612da.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 30,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm33',
      categoriesid: ['c9'],
      title: 'Suan cai',
      imageurl:
          'https://redhousespice.com/wp-content/uploads/2024/05/suan-cai-yu-7-scaled.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 25,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm34',
      categoriesid: ['c9'],
      title: 'Nang dish',
      imageurl:
          'https://asiapioneertravel.com/wp-content/uploads/2023/09/da-nang-food-tour.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 35,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm35',
      categoriesid: ['c10'],
      title: 'fish and chips',
      imageurl:
          'https://forkandtwist.com/wp-content/uploads/2021/04/IMG_0102.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 40,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Affordable),
  EachMixModel(
      id: 'm36',
      categoriesid: ['c10'],
      title: 'hamburgers',
      imageurl:
          'https://www.savorysweetspoon.com/wp-content/uploads/2022/12/Air-Fryer-Hamburgers-1x1-1.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 20,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm37',
      categoriesid: ['c10'],
      title: 'fried chicken',
      imageurl:
          'https://dairyfreeforbaby.com/wp-content/uploads/2023/06/dairy-free-fried-chicken-sq.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 35,
      complaxity: Complaxity.Simple,
      affordability: Affordability.Pricy),
  EachMixModel(
      id: 'm38',
      categoriesid: ['c10'],
      title: 'Homemade Pizza',
      imageurl:
          'https://cdn.loveandlemons.com/wp-content/uploads/2023/02/vegetarian-pizza.jpg',
      ingredients: ['3 Cucomber', '1 Onion', 'Half-Carrot'],
      steps: ['cut the cucomber', 'cut the onion', 'cut the carrot'],
      isoilfree: true,
      issaltfree: true,
      isvegetarian: true,
      duration: 25,
      complaxity: Complaxity.Challenging,
      affordability: Affordability.Affordable),
];
